### ISSUE TITLE
Link to YouTube channel

### ISSUE THREAD

**Issue by surma** [WebAssemblySummit/webassembly-summit.org#108]
https://www.youtube.com/channel/UCh9PqDCdacsTpyRaIryhA8g

 Subtasks:
- add link to Youtube channel
- clarify if this should be placed on the navbar 
- find a place for the items that do not have space on the navbar (on mobile screens in particular)

**Comment by ttraenkler** [comment]
I added the relevant subtasks for this issue. In the simplest case we just place it in the about page or if we place it in the navbar replace the twitter icon.

**Comment by ttraenkler** [comment]
For now I have just added the links to the about page.
