### ISSUE TITLE
Publish schedule

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#110]
Since a first version of the schedule (see #109) has been completed and the conf date is approaching, this could be published at your discretion. We only need to link it in the navigation bar before we announce. Please clarify when we plan to announce exactly. @surma @ashleygwilliams @natorion @torch2424 

(This does and should not block the announcement: We may continue to slightly refine the layout within the boundaries of our consensus to better accommodate the contents on different screen sizes.)

**Comment by surma** [comment]
Please add the menu link ASAP, I’m gonna announce today :) 

Thanks for all the hard work

**Comment by ttraenkler** [comment]
@surma Alright, I am on it.

**Comment by ttraenkler** [comment]
@surma I've opened PR #111 adding the navbar and slight layout fine tuning to get everything ready for the announcement. The normal process would be an approval by @torch2424 or @ashleygwilliams so please sync with them to confirm we're ready to go.
