### ISSUE TITLE
Embed videos for individual talks

### ISSUE THREAD

**Issue by surma** [WebAssemblySummit/webassembly-summit.org#118]
Playlist here:

https://www.youtube.com/playlist?list=PL6ed-L7Ni0yQ1pCKkw1g3QeN2BQxXvCPK

**Comment by torch2424** [comment]
@ttraenkler @ashleygwilliams I've been super busy with new job stuff. Would ya'll be down to pick this up? Otherwise I can try and get it done sometime this weekend before my onboarding :smile:

**Comment by ttraenkler** [comment]
Sure, I will do this. Was planning to do this after work yesterday but a family member got hospitalised.

**Comment by pranjal9599** [comment]
Hey i can embed the talks which page should be more suitable i was thinking of adding youtube links in schedule page and then embed on every individual speaker page?

**Comment by ttraenkler** [comment]
Hi @pranjal9599, thanks for offering your help. Let's place it only on the indidivual speaker pages. While  I proposed to add abstract and picture to the schedule, our consensus was to keep this information on the individual speaker page.

**Comment by pranjal9599** [comment]
Added on the speaker pages keynotes one need some work 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15066223/75012273-aacc2a80-54a7-11ea-941c-809b3b3f5f29.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15066223/75012335-c0415480-54a7-11ea-9980-5ef059b5a463.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15066223/75012591-51b0c680-54a8-11ea-8dc1-fe5ff7b8f4ed.png">

**Comment by ttraenkler** [comment]
@pranjal9599 Cool, thanks! I feel the cards look a bit unbalanced now next to the videos - we could either try to fix them or just remove them altogether, what do the others think? About the collapsing layout for the keynote talks, I had a fix for this in the branch referenced here if that helps that was not merged if you want to peek. This not only fixed the collapsing layout, but also made the cards a bit taller to take up the space better and the same format as the once on the speakers page, which you might try out if it looks better. https://github.com/WebAssemblySummit/webassembly-summit.org/pull/97

**Comment by ttraenkler** [comment]
@pranjal9599 Please let me know if you are still working on this. I am currently sick - in case you are not let me know then I will take over once I have recovered.

**Comment by pranjal9599** [comment]
Hi @ttraenkler I got caught up in somethings will try to make them by tonight or else you can take over. Hope you recover soon.

**Comment by ttraenkler** [comment]
@pranjal9599 OK, I will take over now. I have still not recovered but it should only take a few minutes.

**Comment by ttraenkler** [comment]
@pranjal9599 I've merged your branch into mine, fixed the layout problems on desktop, removed the speaker cards plus some minor refinements (for screenshots see #120).
