### ISSUE TITLE
The site refers to suspended twitter account @WasmSummit 

### ISSUE THREAD

**Issue by bashor** [WebAssemblySummit/webassembly-summit.org#127]
Also, there is https://twitter.com/Wasm_Summit, which one is right?

**Comment by surma** [comment]
Well, we created @wasmsummit a couple weeks ago. And it got suspended for some random reason (it was unused?!). We filed an appeal and never heard anything back. So we created @wasm_summit like a couple hours ago. It’s now updated :)
