### ISSUE TITLE
No link to Twitter in FAQ

### ISSUE THREAD

**Issue by tchetwin** [WebAssemblySummit/webassembly-summit.org#136]
> # How do I find you on Twitter?
>
> There will be a dedicated Twitter account for the WasmSummit conference. Details will be shared here soon!

https://github.com/WebAssemblySummit/webassembly-summit.org/blob/dev/src/faq.md#how-do-i-find-you-on-twitter

Is it https://twitter.com/wasm_summit? I see the Twitter account was [created](http://www.twitterjoindate.com/search?utf8=%E2%9C%93&name=wasm_summit&commit=Search) the same day as that PR was [merged](https://github.com/WebAssemblySummit/webassembly-summit.org/pull/123#event-4054048589). Also the URL was updated that day https://github.com/WebAssemblySummit/webassembly-summit.org/commit/495264608b0c3d24565026e875430183d7dd80db.

**Comment by surma** [comment]
Ah thanks for flagging! That’s an oversight on my end :)

**Comment by tchetwin** [comment]
Fixed in https://github.com/WebAssemblySummit/webassembly-summit.org/commit/4a91725237ac172bc4d7ee40c533d0724d9321bb
