### ISSUE TITLE
Add deadline for tickets and CfP

### ISSUE THREAD

**Issue by surma** [WebAssemblySummit/webassembly-summit.org#23]

**Comment by torch2424** [comment]
@ashleygwilliams @ttraenkler What do we think about this:

<img width="910" alt="Screen Shot 2019-12-03 at 5 55 34 PM" src="https://user-images.githubusercontent.com/1448289/70105647-50cd6e80-15f6-11ea-8ddd-2f635e39c753.png">
<img width="346" alt="Screen Shot 2019-12-03 at 5 56 42 PM" src="https://user-images.githubusercontent.com/1448289/70105648-51660500-15f6-11ea-9c38-83b5f64eb5f7.png">

On mobile, I'll add a mobile specific `<br />` tag to go ahead and make sure they are on seperate lines 😄

**Comment by surma** [comment]
You could also wrap “Application deadline” and “December 9th, 2019” in separate `<nobr>` tags.

**Comment by ttraenkler** [comment]
@torch2424 Shorten to "Application closes December 9th" and highlight it a bit in light yellow?

**Comment by torch2424** [comment]
@surma 

TIL about [`<nobr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr) 😂 

@ttraenkler 

How about this?

<img width="861" alt="Screen Shot 2019-12-04 at 1 58 29 PM" src="https://user-images.githubusercontent.com/1448289/70185220-364ed000-169e-11ea-9076-2f6c97aca90b.png">
<img width="345" alt="Screen Shot 2019-12-04 at 1 58 41 PM" src="https://user-images.githubusercontent.com/1448289/70185222-364ed000-169e-11ea-8b5c-a18a132b9ba2.png">

**Comment by torch2424** [comment]
Per @ashleygwilliams and my suggestion in the discord, going back to white text:

<img width="883" alt="Screen Shot 2019-12-04 at 2 04 08 PM" src="https://user-images.githubusercontent.com/1448289/70185622-00f6b200-169f-11ea-89bf-2a9279a5ceba.png">
<img width="345" alt="Screen Shot 2019-12-04 at 2 04 16 PM" src="https://user-images.githubusercontent.com/1448289/70185623-00f6b200-169f-11ea-8996-c9b28f30936e.png">

Is this looking good to go? 😄 👍

**Comment by torch2424** [comment]
Got approval from @ashleygwilliams over discord, will open a PR later today 😄

**Comment by ttraenkler** [comment]
@torch2424 white looks better I agree. Thanks!
