### ISSUE TITLE
Add a link to a markdown version of FAQ

### ISSUE THREAD

**Issue by torch2424** [WebAssemblySummit/webassembly-summit.org#31]
relates to #24 

This should write the content for the faq, and linked to on the website as a markdown file (similar to the code of conduct). And migrated to #30 after the applications close 😄

**Comment by ttraenkler** [comment]
@torch2424 Thanks for the swift implementation with regards to the deadline! I see a problem with the mobile layout, but otherwise it's ready to get merged imho
