### ISSUE TITLE
design speakers page

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#37]
For the upcoming announcements of the speakers and the schedule, we need a general page design and specific page layouts. It should fit with the design of the rest of the pages, show pictures of the speakers. note the schedule page has been moved to a different issue

**Comment by ttraenkler** [comment]
I have started working on this issue and will come up with a proposal soon.

**Comment by ttraenkler** [comment]
Here a first attempt at the design of content pages, applied to the about page. 

<img width="1440" alt="Bildschirmfoto 2020-01-04 um 00 00 46" src="https://user-images.githubusercontent.com/347722/71754197-8085c580-2e85-11ea-9af5-fe891629c2e1.png">

The number of columns will adapt to the width of the screen and the title "About the Event" will scroll off page while the navbar is sticky. 

I will probably refine the alignment of the nav items and overall do a couple of more large or small changes and iterations, but since we need to get this out soon I thought better gather some early feedback now on the current state of things to see if people like this direction.

**Comment by torch2424** [comment]
I think this is good, and we can move forward with this for now :smile: :+1:

**Comment by ttraenkler** [comment]
Cool. I will need to finish some layout refinements such as the mobile version of the navbar, then we can ship it in a first version. Then I will continue with the speaker and schedule page.

**Comment by ttraenkler** [comment]
Applied the navigation bar to the main page and am working on a burger menu for mobile layouts:

<img width="365" alt="Bildschirmfoto 2020-01-05 um 19 23 49" src="https://user-images.githubusercontent.com/347722/71784200-11c57b00-2ff1-11ea-8dd3-4e677e6402a0.png">
<img width="1193" alt="Bildschirmfoto 2020-01-05 um 19 22 51" src="https://user-images.githubusercontent.com/347722/71784202-125e1180-2ff1-11ea-8c10-fd0bb6e98864.png">
<img width="364" alt="Bildschirmfoto 2020-01-05 um 19 28 18" src="https://user-images.githubusercontent.com/347722/71784245-93b5a400-2ff1-11ea-9e9a-3b83f1919c37.png">

**Comment by ttraenkler** [comment]
I have refined the design of the navigation bar and added mobile support. I replaced the links on the front page with the navigation bar. The navigation items I would see fit are "News, Speakers, Schedule, Venue, About". The about page contains the FAQ, including the contact email, Twitter, and code of conduct links. I have also added refined the text and added some items to the FAQ (e.g. hotel recommendations and the Discord channel) - see the screenshots below. Let me know what you think, this could be merged before continuing on the speaker and schedule page, which in the first instance I would derived from the about page template.

<img width="1440" alt="Bildschirmfoto 2020-01-07 um 03 17 06" src="https://user-images.githubusercontent.com/347722/71863138-44a86580-30fc-11ea-8830-573902448def.png">
<img width="372" alt="Bildschirmfoto 2020-01-07 um 03 18 18" src="https://user-images.githubusercontent.com/347722/71863196-6ace0580-30fc-11ea-9941-89c069f1dd02.png">
<img width="1440" alt="Bildschirmfoto 2020-01-07 um 03 17 09" src="https://user-images.githubusercontent.com/347722/71863200-6dc8f600-30fc-11ea-978b-cc2ffa4b53de.png">
<img width="1440" alt="Bildschirmfoto 2020-01-07 um 03 17 15" src="https://user-images.githubusercontent.com/347722/71863202-702b5000-30fc-11ea-9593-2b0d5098ec44.png">

**Comment by ttraenkler** [comment]
Here is a first draft of the speakers page:

![Bildschirmfoto 2020-01-07 um 17 42 32](https://user-images.githubusercontent.com/347722/71912325-980aca00-3175-11ea-9d57-4e94ea16fd12.png)

**Comment by ttraenkler** [comment]
Lighthouse reported accessibility issues due to missing headline and alt image texts - see #52.

**Comment by ashleygwilliams** [comment]
this is done! closing
