### ISSUE TITLE
Add offline support

### ISSUE THREAD

**Issue by torch2424** [WebAssemblySummit/webassembly-summit.org#41]
One thing that would be great is if the website was available offline, in case any attendees have a poor connection at the event.

**Comment by ttraenkler** [comment]
steps here: https://nextjs.org/features/progressive-web-apps#offline-support

```
yarn add next-offline
touch static/manifest.json
```

wrap config with next-offline https://github.com/hanford/next-offline#usage

**Comment by ttraenkler** [comment]
Until I am able to resume work on this task, I will assign it back to you @torch2424. I've added you and @ashleygwilliams to the forked repo as admin in case you want to continue experimenting with it on a github setup.

**Comment by ttraenkler** [comment]
done, pr see #58
