### ISSUE TITLE
Design schedule page

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#45]
schedule page with speakers talk title abstract, time etc.
example data here: https://gist.github.com/ashleygwilliams/6f3a16ac89383e024fe71894a6a2a4d9

example: https://developer.chrome.com/devsummit/schedule/

**Comment by torch2424** [comment]
Just for reference, this page should have the content from #40 😄

**Comment by torch2424** [comment]
I am currently working on this on the branch: `45-schedule-page`.

And this is the current design:

![Screenshot from 2020-01-15 19-39-05](https://user-images.githubusercontent.com/1448289/72491394-c9ffda00-37ce-11ea-83fd-82f030e739e8.png)

Where if you hove over an item's title and description, it will be underlined, and will link to the respective talk :smile: 

Thoughts? @ashleygwilliams @ttraenkler :smile: :+1:

**Comment by ttraenkler** [comment]
@torch2424 Thanks for the design proposal! I like the schedule icon and the font sizes for the time and speakers. Here are a few ideas that came to my mind to make use of the available space and improve the visual grouping, but feel free to go in another direction if you have a design in mind that you like.

- About refining the line, how do you feel about making it a bit thinner and a train stop timetable plan (dash / circle) like here: https://developer.chrome.com/devsummit/schedule/ ? (You can achieve that with border-radius 100%) + a few more vw margin between the line and the speakers?
- What about a bit more margin on the left in vw (viewport width) units and below the headline in vh that adapts to the screen size?
- Since we're not yet using much of the width of the screen, maybe we could put the time in a column left of the speaker/title and flex it so it wraps when width becomes to small.
- A bit more vh spacing between the talks would make them group better
- This one I am not sure about: Maybe we could try adding boxes around speaker/talk title similar to here https://developer.chrome.com/devsummit/schedule/ with the same dark purple on the cards / the navbar (the variable I think is navbarBlue)? Then instead of the underline one could outline the box on hover. Just guessing, would have to try out how it looks!

**Comment by ttraenkler** [comment]
@torch2424 One thing that I did not mention is that if we keep both the schedule and the speakers page we will run out of button space on smartphones, so we would probably have to move one of the other buttons. 

I see that you removed the speakers link - is that intentional? If I understand correctly you propose to replace the speakers page with the schedule?

**Comment by torch2424** [comment]
@ttraenkler 

> Thanks for the design proposal! I like the schedule icon and the font sizes for the time and speakers.

You are welcome! Thanks, glad you like them 😄 

> About refining the line, how do you feel about making it a bit thinner and a train stop timetable plan (dash / circle) like here: https://developer.chrome.com/devsummit/schedule/ ? (You can achieve that with border-radius 100%) + a few more vw margin between the line and the speakers?

So personally, I felt like the CDS deisgn for their timetable was a little too busy. I don't feel super strong about it, but the schedule design I enjoyed the most personally was [JSConfEU](https://2019.jsconf.eu/schedule/timetable.html). For some reason, as an atendee, I found it to be the easiest to figure out when something, and relative to other events in the day if that makes sense?

> What about a bit more margin on the left in vw (viewport width) units and below the headline in vh that adapts to the screen size?

So I am having a hard visualizing that, would you mind going into devtools / photoshop and making a quick mock? Or if not, you specify more margin on  the left. But of the left of what? The entire schedule? Between the left line and text?

> Since we're not yet using much of the width of the screen, maybe we could put the time in a column left of the speaker/title and flex it so it wraps when width becomes to small.

Oh that's a good idea! But when it does wrap, should each item fold underneath the respective time? I think that might look a little awkward if the time was super large, with large text underneath?

> A bit more vh spacing between the talks would make them group better

Awesome! Yeah right now it's just 10px of space between them. Do you want to use vh units? May I ask why? On a taller display (like a tablet) I feel like it could give very different looking results? Maybe I can set it to 20px? Or rems?

> This one I am not sure about: Maybe we could try adding boxes around speaker/talk title similar to here https://developer.chrome.com/devsummit/schedule/ with the same dark purple on the cards / the navbar (the variable I think is navbarBlue)? Then instead of the underline one could outline the box on hover. Just guessing, would have to try out how it looks!

So do you mean the chat looking boxes? E.g

<img width="513" alt="Screen Shot 2020-01-16 at 4 43 43 PM" src="https://user-images.githubusercontent.com/1448289/72574849-5f5aa700-387f-11ea-80a3-8c6b8500e682.png">

So how would that fit into the current design? Though, I think it make sense if you feel strongly about the train stop looking design, so we might want to decide that first.

Though, outlining the elements on hover I think could make a cool looking design, making them look more "clickable". So We can try that if we decide to go with boxes.

 > One thing that I did not mention is that if we keep both the schedule and the speakers page we will run out of button space on smartphones, so we would probably have to move one of the other buttons. I see that you removed the speakers link - is that intentional? If I understand correctly you propose to replace the speakers page with the schedule?

Yep, I totally noticed that! I think we should probably remove some of the social links on mobile, and preserve the info links for mobile. I did not remove the speakers intentionally (I think), I think I may have just made my branch before the speakers were pushed out 😄

**Comment by ttraenkler** [comment]
> So personally, I felt like the CDS deisgn for their timetable was a little too busy. I don't feel super strong about it, but the schedule design I enjoyed the most personally was JSConfEU. For some reason, as an atendee, I found it to be the easiest to figure out when something, and relative to other events in the day if that makes sense?

Fine if you want to go with a model similar to https://2019.jsconf.eu/schedule/timetable.html - the only problem we have is we don't have parallel tracks so we won't fill much of the screen space on desktop screens - therefore my suggestion was to add more margin depending on the screen width. Would also probably look nicer with a dark blue background like on JSConf EU.

> So I am having a hard visualizing that, would you mind going into devtools / photoshop and making a quick mock? Or if not, you specify more margin on the left. But of the left of what? The entire schedule? Between the left line and text?

Left being left of everything - since with a fixed px margin the wider the screen the more a fixed pixel size from the left will look "lost in space" if that makes sense - e.g. on a desktop monitor in fullscreen with devtools closed.

> Oh that's a good idea! But when it does wrap, should each item fold underneath the respective time? I think that might look a little awkward if the time was super large, with large text underneath?

Or we use breakpoints and adapt the layout to your liking for "mobile" = narrow screens.

> Awesome! Yeah right now it's just 10px of space between them. Do you want to use vh units? May I ask why? On a taller display (like a tablet) I feel like it could give very different looking results? Maybe I can set it to 20px? Or rems?

px could also be fine. I just thought on smartphones you want more on the screen while on laptop / desktop screens you want the text to breath more.

> So how would that fit into the current design? Though, I think it make sense if you feel strongly about the train stop looking design, so we might want to decide that first. Though, outlining the elements on hover I think could make a cool looking design, making them look more "clickable". So We can try that if we decide to go with boxes.

Let's just go ahead with your JSConf EU proposal then.

> Yep, I totally noticed that! I think we should probably remove some of the social links on mobile, and preserve the info links for mobile. I did not remove the speakers intentionally (I think), I think I may have just made my branch before the speakers were pushed out 😄

Yeah maybe we put the social media links on the landing page in the content area instead, that would make sense. (I noticed the landing page still does not fit on one screen for some reason on my phone.) Generally I would also be open with merging the speaker cards and abstracts into the schedule, since we have only a short abstract to place and I agree we're duplicating most of the content, but since this might take more time and discussion than we're ready to have, I am just mentioning this is a theoretic possibility, not something I would push for.

**Comment by torch2424** [comment]
Cool I'll take this feedback and propose a new design later tonight 😄

**Comment by ttraenkler** [comment]
I had some free time today so I did some trial and error visual experimentation with the layout of the speaker page #62.

With your proposal in the back of my mind, I thought like on https://rustconf.com/schedule#rust-for-weld-a-high-performance-parallel-jit-compiler we should put the talk abstracts below each other instead of one per page. This is both more convenient to browse instead of going back and forth as well as filling the available space better. It also duplicates less content and eliminates to switch 20 times between pages to read all abstracts. 

I realised this would duplicate most of the schedule page, so I tried to see how it would look like if we integrate your proposal of a design similar to the schedule of JSConf EU 2019 with the speaker/talk page, so I added the left dash and the times like on JSConf EU and mixed in the styles of the about page and the train stop thing to see how it looks and I think it kinda works!

How do you feel about it? Should we go along this route?

<img width="1440" alt="Bildschirmfoto 2020-01-18 um 23 10 48 (2)" src="https://user-images.githubusercontent.com/347722/72671261-d9d62300-3a47-11ea-9437-54ef7058bf89.png">
<img width="398" alt="Bildschirmfoto 2020-01-18 um 20 18 57" src="https://user-images.githubusercontent.com/347722/72671265-e9556c00-3a47-11ea-9313-ddc667936d58.png">

**Comment by torch2424** [comment]
@ttraenkler So I like your time design! Totally down to do the schedule like this, I agree it looks great, and it's a nice compromise between our two suggstions haha!

However, The schedule needs to include more things than just the speakers. Such as food / coffee times. Therefore, I think it might be good to preserve the current speaker design (As it highlights the speaker instead of the time), but then move forward with this design for the talks?

What do you think? :smile:

**Comment by ttraenkler** [comment]
@torch2424 Yes, I am happy about the result - it blends our ideas nicely! Thanks for your great input as always! I agree we should keep the /speakers page with all the speaker cards. 

Tomorrow I plan to open a PR for the schedule page. With this we should be ready to go - I hope, then all we need is the schedule data and after inserting it as always check that the layout is robust enough to accommodate the content.

**Comment by ttraenkler** [comment]
@torch2424 asked me to not open a PR for this (my work is in feature/62-speaker-page). Instead he proposed to merge the proposed layout into his branch instead (see PR).

**Comment by ttraenkler** [comment]
@torch2424 I've noticed the left margin on mobile is still there, some titles span up to 8 lines at the moment.

<img width="543" alt="Bildschirmfoto 2020-01-23 um 13 12 14" src="https://user-images.githubusercontent.com/347722/72983650-1310e900-3de2-11ea-914e-efab4d7b6c07.png">

**Comment by torch2424** [comment]
@ttraenkler Ah sorry just saw this, I was super sick yesterday. By left margin, do you mean the space between the time and the circle? Or do you want the entire schedule closer to the left edge?

My apologies! I could have sworn this is how your branch looked when I tried it on mobile 😯

**Comment by ttraenkler** [comment]
@torch2424 No worries, I think it's good enough. Since I am done with my part, I am just refining a little bit if we still have time and will. More important obviously is getting the data in, this should not block the announcement.

If you compare the screenshot of my branch above, I maximised the width of the text to the possible extent with the time on the left to minimise the problem a little bit to the extent possible with the layout with time on left. Probably it would be better to place the time differently on mobile, but I didn't have time to play with it so far.

**Comment by torch2424** [comment]
@ttraenkler Cool, thanks for the explanation! If I get the time, I'll play around with moving around the time in a different place for mobile 😄
