### ISSUE TITLE
Add link to livestream

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#60]
We should plan how to embed the livestream with some time in advance so we can avoid last minute actions or not having a livestream. I assume @natorion or @surma you know most about this?

- Who is going to take care of the livestream setup?
- Who is going to take care of recording the talks on site?
- What is the URL of the livestream?
- Do we just link to a Youtube URL or do we want to embed the livestream in the summit website itself? I have already added a Youtube button to the navbar but it is currently disabled as we don't know where it should link to.

**Comment by natorion** [comment]
We are going to meet with the AV eng person next week. After that I can share more details.

> Who is going to take care of the livestream setup?
Google AV eng person at the venue
> Who is going to take care of recording the talks on site?
Google AV eng person at the venue
> What is the URL of the livestream?
Not known yet.
> Do we just link to a Youtube URL or do we want to embed the livestream in the summit website itself? I have already added a Youtube button to the navbar but it is currently disabled as we don't know where it should link to.
I will check with the AV eng person. I don't think we need to embed something into the website. A link to the livestream is IMO enough.
If we are using YT for livestreaming, I guess we can use the Chromium/ChromeDevelopers channel.

**Comment by ashleygwilliams** [comment]
since we'll need to be publishing videos- i think it would be useful for us to set up our own youtube channel- since we'll need continued access for moderating comments, etc

**Comment by surma** [comment]
@natorion Do you mind checking in with the tech team on what our constraints are? Can we stream to any YouTube channel we own?

**Comment by natorion** [comment]
Sure let's check tomorrow.

**Comment by ttraenkler** [comment]
closed in favour of #108
