### ISSUE TITLE
Design speaker page

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#62]
We need a dedicated speaker page for each of the speakers with infos about the speaker and the talk.
Here is an example from JSConf EU https://2019.jsconf.eu/speakers/ - you can click on the speakers to go to their speaker page

This page should of course also contain name and picture and have space for a longer bio, title and abstract of the talk and later embed the video of their talk, links to their github, twitter, and homepage and potentially a transcript.

@ashleygwilliams you said you will take this on in conjunction with #39. If you need any help or want me to add an animation for the transition between the speakers and speaker page let me know.

**Comment by ttraenkler** [comment]
@ashleygwilliams: As requested I will take over this task based on this example data:

- https://gist.github.com/ashleygwilliams/6f3a16ac89383e024fe71894a6a2a4d9
- https://2019.jsconf.eu/ashley-williams/javascripts-journey-to-the-edge.html

**Comment by ttraenkler** [comment]
PRs #92, #93 have been merged, #97 pending

**Comment by ashleygwilliams** [comment]
this has been closed
