### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#68]
Some people have readability problems with white text on purple background. People prefer reading black on white, we might also think of white on a dark color. While we have not any reports about this yet, this was rerported for https://webassembly.eu which has a similar color scheme.

I experimented with black on white for the about page in #55 - see screenshots there. We should decide whether this is a necessary change and if so how it should look.

**Comment by ttraenkler** [comment]
This is one of the current experiments for feedback

<img width="1440" alt="Bildschirmfoto 2020-01-09 um 05 21 24" src="https://user-images.githubusercontent.com/347722/72157535-7a797280-33b8-11ea-893d-d5d70cb35858.png">

**Comment by ashleygwilliams** [comment]
we are going to keep this color scheme for this year and can consider other color schemes for next year
