### ISSUE TITLE
address console warning

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#70]
address console warning

`The resource https://webassembly-summit.org/_next/static/Ml_-vciM3K0r64bCT_mSl/pages/about.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

**Comment by ttraenkler** [comment]
seems to be a non-issue:
https://github.com/zeit/next.js/issues/6517#issuecomment-469063892

**Comment by okeybond** [comment]
> seems to be a non-issue:
> [vercel/next.js#6517 (comment)](https://github.com/vercel/next.js/issues/6517#issuecomment-469063892)

Sorry, it's still an issue
<img width="384" alt="Screenshot 2020-06-01 at 15 21 04" src="https://user-images.githubusercontent.com/48156152/83418554-b1116180-a41b-11ea-952f-6b6e1a333ad7.png">
