### ISSUE TITLE
Service worker looking for outdated .js bundles

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#87]
After the latest the deployment I noticed the font on the speakers page is not rendered correctly. Opening the console, I found 404s on https://webassembly-summit.org/speakers. On the other routes I don't get the 404s but nevertheless the bad-precaching-response.

speakers:1 GET https://webassembly-summit.org/_next/static/wXMJzV_JnmWQNVu98m8GP/pages/speakers.js net::ERR_ABORTED 404
PrecacheController.mjs:194 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://webassembly-summit.org/_next/static/chunks/commons.43171be2915a298a1ac7.js?__WB_REVISION__=546453f9928c5e8eeabe","status":404}]
    at l.o (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1749)
    at async Promise.all (index 0)
    at async l.install (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1221)
n @ WorkboxError.mjs:30
o @ PrecacheController.mjs:194

This relates to the service worker introduced in #41.

**Comment by ttraenkler** [comment]
It seems the service worker is looking for the old Javascript bundles with an outdated filename hash suffix. 

There is an open issue for this for the package `next-offline` we're using with unfortunately no fix so far:
https://github.com/hanford/next-offline/issues/190

One option would be to disable the service worker:
https://github.com/hanford/next-offline/issues/81

What I will try as a workaround however is keeping the old Javascript bundles around instead of deleting them at each deployment.

**Comment by ashleygwilliams** [comment]
we've removed the service worker so we no longer need this
