### ISSUE TITLE
Setup sentry to log client side errors

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#88]
Not only in light of #87 it might be helpful to add sentry for logging client side errors in the browser console to get notified of any problems users are having.

Setting this up is quite easy: https://docs.sentry.io/error-reporting/quickstart/?platform=browsernpm

@ashleygwilliams: Could you create an account for the org?

**Comment by ashleygwilliams** [comment]
i think this is too much  for a simple conference page, closing
