### ISSUE TITLE
Add speaker intros & biographies

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassembly-summit.org#96]
A lot of people watching the talks will not know all the speakers and their background. Also, for some talks we have no content at all, no abstract or bio, so the speaker pages are currently mainly empty. Imho we should write short intros + biographies for the speakers from the public knowledge found on the web about the speakers.

We should maybe also reach out to the speakers and ask for a bio, and whether they want their Twitter account, and personal homepage linked if they did not provide a link in the CfP.

/cc @ashleygwilliams @torch2424 @natorion @surma

**Comment by ashleygwilliams** [comment]
We are not doing speaker bios

**Comment by ttraenkler** [comment]
Today we discussed a short profile on the speakers card instead of duplicating talk title and time would make sense but is not possible for the same reason as this issue - we don't have the data and won't have time to ask for the consent of the speakers for profiles derived from their public profiles. Conclusion: Something to keep in mind for next year.
